version: '3'

services:
  bot:
    build: .
    depends_on:
      - db
    environment:
      POSTGRES_DB: telegrambot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    ports:
      - "8080:8080"
  db:
    image: postgres
    environment:
      POSTGRES_DB: telegrambot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - ./postgres-data:/var/lib/postgresql/data